---- Base app schema

-- User
-- noinspection SqlResolve @ routine/"gen_random_uuid"
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Project
CREATE TABLE project (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties
  owner_id BIGINT NOT NULL,
  name varchar(256) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Task
CREATE TABLE task (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FK
  project_id BIGINT NOT NULL,
  
  -- Properties
  title varchar(256) NOT NULL,
  done bool NOT NULL DEFAULT false,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- TaskRecord
CREATE TABLE taskprogress (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FK
  task_id BIGINT NOT NULL,

  -- Properties
  progress INT NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP with time zone NOT NULL
);

-- TaskProgress
CREATE TABLE timerecord (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FK
  task_id BIGINT NOT NULL,

  -- Properties
  place varchar(256) NOT NULL,
  start_time TIMESTAMP with time zone NOT NULL,
  stop_time TIMESTAMP with time zone NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP with time zone NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP with time zone NOT NULL
);

ALTER TABLE task ADD CONSTRAINT fk_project
  FOREIGN KEY (project_id) REFERENCES project(id)
  ON DELETE CASCADE;

ALTER TABLE taskprogress ADD CONSTRAINT fk_task
    FOREIGN KEY (task_id) REFERENCES task(id)
        ON DELETE CASCADE;

ALTER TABLE timerecord ADD CONSTRAINT fk_task
    FOREIGN KEY (task_id) REFERENCES task(id)
        ON DELETE CASCADE;
